---
- hosts: all
  user: root
  roles:
    - { role: cleanup, when: (OPENSHIFT_AWS_INSTALL_CLEANUP | default(False) | bool) or (OPENSHIFT_LIBVIRT_INSTALL_CLEANUP | default(False) | bool) }
    - { role: install, when: OPENSHIFT_INSTALL | default(False) | bool }
      #    - { role: post-install, when: OPENSHIFT_INSTALL | default(False) | bool }
