---
- hosts: all
  user: root
  roles:
    - { role: ansible-config, when: OPENSHIFT_INSTALL | default(True) | bool }
    - { role: cleanup, when: (OPENSHIFT_AWS_INSTALL_CLEANUP | default(False) | bool) or (OPENSHIFT_LIBVIRT_INSTALL_CLEANUP | default(False) | bool) }
    - { role: install, when: OPENSHIFT_INSTALL | default(True) | bool }
    - { role: quickstart, when: OPENSHIFT_INSTALL | default(True) | bool }
    - { role: post-install, when: OPENSHIFT_INSTALL | default(False) | bool }
     
- hosts: controller
  user: root
  roles:
    - { role: controller-kickstart, when: OPENSHIFT_INSTALL | default(False) | bool }
    - { role: disable-selinux, when: (OPENSHIFT_INSTALL | default(False) | bool) and (DISABLE_SELINUX | default(False) | bool) }
    - { role: node-config, when: OPENSHIFT_INSTALL | default(False) | bool }
      #    - { role: ssh-config, when: OPENSHIFT_INSTALL | default(False) | bool }

- hosts: nodes
  user: root
  roles:
    - { role: node-config, when: OPENSHIFT_INSTALL | default(False) | bool }
    - { role: selinux, when: OPENSHIFT_INSTALL | default(False) | bool }
    - { role: disable-selinux, when: (OPENSHIFT_INSTALL | default(False) | bool) and (DISABLE_SELINUX | default(False) | bool) }
