---
- hosts: all
  user: root
  roles:
    - { role: cleanup, when: (OPENSHIFT_AWS_INSTALL_CLEANUP | default(False) | bool) or (OPENSHIFT_LIBVIRT_INSTALL_CLEANUP | default(False) | bool) }
    - { role: install, when: OPENSHIFT_INSTALL | default(True) | bool }
    - { role: post-install, when: OPENSHIFT_INSTALL | default(True) | bool }
     
- hosts: controller
  user: root
  roles:
    - { role: controller-kickstart, when: OPENSHIFT_INSTALL | default(True) | bool }
    - { role: node-config, when: OPENSHIFT_INSTALL | default(True) | bool }
