---
- hosts: all
  user: root
  tasks:
    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - golang
        - gcc
        - git
        - golang-bin 
        - gcc-c++

    - name: create gopath dir
      file:
        path: "{{ GOPATH | default('/root/.go') }}"
        state: directory

    - name: set workdir
      set_fact:
        workdir: "{{ GOPATH }}/src/github.com/openshift/installer"

    - name: cleanup installer code if it exists
      file:
        path: "{{ workdir }}"
        state: absent

    - name: cleanup vars file
      file:
        path: /tmp/ocp-env.sh
        state: absent

    - name: get the installer and its dependencies
      shell: go get "{{ item }}"
      with_items:
        - github.com/openshift/installer/data
      environment:
        GOPATH: "{{ GOPATH }}"

    - name: build installer binary
      shell: cd {{ workdir }}; hack/build.sh"
      environment:
        GOPATH: "{{ GOPATH }}"

    - name: get terraform binary
      shell: cd {{ workdir }}; hack/get-terraform.sh"
      environment:
        GOPATH: "{{ GOPATH }}"

    - name: copy the script containing the OCP vars
      template:
        src: ocp-aws-env.sh.j2
        dest: /tmp/ocp-env.sh
        mode: 0755
      when: OPENSHIFT_INSTALL_PLATFORM == "aws"

    - name: installer config
      shell: "source /tmp/ocp-env.sh; cd {{ workdir }}; bin/openshift-install create install-config"
      
    - name: manifests
      shell: "source /tmp/ocp-env.sh; cd {{ workdir }}; bin/openshift-install create manifests"

    - name: ignition configs
      shell: "source /tmp/ocp-env.sh; cd {{ workdir }}; bin/openshift-install create ignition-configs"
    
    - name: set the user in ignition configs
      replace:
        path: "{{ item }}"
        regexp: "core"
        replace: "{{ OPENSHIFT_INSTALL_USER }}"
      with_items:
        - "{{ workdir }}/bootstrap.ign"
        - "{{ workdir }}/master.ign"
        - "{{ workdir }}/worker.ign"
    
    - block:
       - name: download the image
         get_url:
           url: "{{ OPENSHIFT_IMAGE_URL }}"
           dest: /root/rhcos-qemu.qcow2.gz

       - name: run openshift installer on libvirt
         shell: "source /tmp/ocp-env.sh; cd {{ workdir }}; bin/openshift-install create cluster --log-level=debug"
      when: OPENSHIFT_INSTALL_PLATFORM == "libvirt"

    - block:
        - name: run openshift installer on aws
          shell: "source /tmp/ocp-env.sh; cd {{ workdir }}; bin/openshift-install create cluster --log-level=debug"
      when: OPENSHIFT_INSTALL_PLATFORM == "aws"

    - name: ensure that .kube dir exists
      file:
        path: /root/.kube
        state: directory

    - name: copy the kubeconfig
      copy:
        src: "{{ workdir }}/auth/kubeconfig"
        dest: /root/.kube/config

    - name: pick one master node
      shell: oc get nodes -l node-role.kubernetes.io/master | awk 'NR>1 {print $1}' | tail -n1
      register: controller_node

    - name: remove the label on one of the masters
      shell: oc label node {{ controller_node.stdout }} node-role.kubernetes.io/master-

    - name: add the controller label
      shell: oc label node {{ conroller_node.stdout }} {{ item }}
      with_items:
        - "node-role.kubernetes.io/controller=true"
        - "role=controller"

    - name: controller node
      debug:
        msg: "The controller node is {{ controller_node.stdout }}"
        
    - name: ensure that .kube dir exists on controller
      file:
        path: /root/.kube
        state: directory
      delegate_to: "{{ controller_node.stdout }}"

    - name: copy the kubeconfig to controller node
      copy:
        src: "{{ workdir }}/auth/kubeconfig"
        dest: /root/.kube/config
      delegate_to: "{{ controller_node.stdout }}"

    - name: copy perf private key to controller host
      copy:
        src: /root/.ssh/id_rsa
        dest: /root/.ssh/id_rsa
        mode: 0600
      delegate_to: "{{ controller_node.stdout }}"

    - name: copy clusterloader binary
      copy:
        src: /usr/libexec/atomic-openshift/extended.test
        dest: /root/extended.test
      delegate_to: "{{ controller_node.stdout }}"

    - name: disable selinux in crio config
      lineinfile:
        path: /etc/crio/crio.conf
        regexp: '^selinux'
        line: 'selinux = false'
      delegate_to: "{{ controller_node.stdout }}"

    - name: restart crio
      service:
        name: crio
        state: restarted
      delegate_to: "{{ controller_node.stdout }}"
