---
- name: set workdir
  set_fact:
    workdir: "{{ GOPATH }}/src/github.com/openshift/installer"

- name: ensure that .kube dir exists on controller
  file:
    path: /root/.kube
    state: directory

- name: copy the kubeconfig to controller node
  copy:
    src: "{{ workdir }}/auth/kubeconfig"
    dest: /root/.kube/config

- name: copy perf private key to controller host
  copy:
    src: /root/.ssh/id_rsa
    dest: /root/.ssh/id_rsa
    mode: 0600

- name: copy ssh config
  copy:
    src: config
    dest: /root/.ssh/config
    mode: 0600

- name: copy clusterloader binary
  copy:
    src: /usr/libexec/atomic-openshift/extended.test
    dest: /root/extended.test
    mode: 0755

- name: pbench-controller image
  shell: podman pull docker.io/ravielluri/image:controller

- name: nodes
  shell: oc get nodes | awk 'NR>1 {print $1}'
  register: ocp_nodes

- name: add nodes to group
  add_host: name={{ item }} groups=nodes
  with_items:
    - "{{ ocp_nodes.stdout_lines }}"
