---
- name: set workdir
  set_fact:
    workdir: "{{ GOPATH }}/src/github.com/openshift/installer"

- name: vars path
  set_fact:
    openshift_vars_file: "{{ansible_env.HOME}}/ocp-env.sh"

- name: ensure that .kube dir exists
  file:
    path: /root/.kube
    state: directory

    #- name: masters
    #shell: oc get nodes | grep master | awk '{print $1}'
    #register: ocp_masters

- name: copy the kubeconfig
  copy:
    src: "{{ workdir }}/auth/kubeconfig"
    dest: /root/.kube/config

- name: stat svt repo
  stat:
    path: /root/svt
  register: svt

- name: clone svt repo
  git:
    repo: https://github.com/openshift/svt
    dest: /root/svt
    update: yes
    version: containerozed_tooling
  when: svt.stat.exists == False

- name: create clusterloader dir
  file:
    path: /usr/libexec/atomic-openshift/
    state: directory

- name: copy clusterloader binary
  copy:
    src: /usr/bin/openshift-tests
    dest: /usr/libexec/atomic-openshift/extended.test
    mode: 0755
